swagger: '2.0'
info:
  title: Тестовое API сервиса КИТ.КАССА
  description: Увеличьте средний чек за счет использования сервиса персональных рекомендаций КИТ.КАССА.
  version: '0.0.3'
host: api.kassa.mintwhale.ru
schemes:
  - http
basePath: /test
produces:
  - application/json

paths:
  /recommendations:
    post:
      summary: Получить рекомендации.
      description: |
        Выдает персональные рекомендации на основании списка товаров.
        Рекомендации отсортированы в порядке убывания вероятности.
      operationId: app.post_recommendations
      parameters:
        - name: products
          in: body
          description: Список товаров.
          required: true
          schema:
            $ref: '#/definitions/ProductsList'
      responses:
        200:
          description: Рекомендованные товары.
          schema:
            type: object
            required:
              - id
              - products
            properties:
              id:
                description: Уникальный идентификатор рекомендации.
                type: string
                pattern: '^[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}$'
              products:
                $ref: '#/definitions/ProductsList'

  /sales:
    post:
      summary: Сохранить историю продаж.
      description: |
        Позволяет накапливать историю продаж для дальнейшего автоматического улучшения качества рекомендаций.
      operationId: app.post_sales
      parameters:
        - name: sales
          in: body
          description: История продаж.
          required: true
          schema:
            type: array
            uniqueItems: true
            minItems: 1
            maxItems: 1000
            items:
              type: object
              required:
                - id
                - products
              properties:
                id:
                  description: Уникальный идентификатор чека.
                  type: string
                  pattern: '^[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}$'
                products:
                  $ref: '#/definitions/ProductsList'
      responses:
        200:
          description: История сохранена.

definitions:
  Product:
    description: Уникальный идентификатор товара.
    type: string
    pattern: '^[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}$'
  ProductsList:
    type: array
    description: Список товаров.
    items:
      $ref: '#/definitions/Product'
    minItems: 1
    maxItems: 100
    uniqueItems: true

securityDefinitions:
  api_key:
    description: Авторизация по ключу API.
    type: apiKey
    name: Api-Key
    in: header

security:
  - api_key: []
