swagger: '2.0'
info:
  title: Тестовое API сервиса КИТ.КАССА
  description: Увеличьте средний чек за счет использования сервиса персональных рекомендаций КИТ.КАССА.
  version: '0.0.1'
host: api.kassa.mintwhale.ru
schemes:
  - http
basePath: /test
produces:
  - application/json

paths:
  /recommendations:
    get:
      summary: Получить рекомендации.
      description: |
        Выдает персональные рекомендации на основании списка товаров.
        Рекомендации отсортированы в порядке убывания вероятности.
      operationId: app.get_recommendations
      parameters:
        - $ref: '#/parameters/ApiKey'
        - name: products
          in: query
          description: Список товаров.
          required: true
          type: array
          # TODO: Избежать дублирования
          items:
            type: string
            pattern: '^[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}$'
          collectionFormat: csv
          minItems: 1
          maxItems: 100
      responses:
        200:
          description: Рекомендованные товары.
          schema:
            $ref: '#/definitions/ProductsList'

  /sales:
    post:
      summary: Сохранить историю продаж.
      description: |
        Позволяет накапливать историю продаж для дальнейшего автоматического улучшения качества рекомендаций.
      operationId: app.post_sales
      parameters:
        - $ref: '#/parameters/ApiKey'
        - name: sales
          in: body
          description: История продаж.
          required: true
          schema:
            type: array
            # TODO: Определить минимальную и максимальную длину истории
            items:
              type: object
              required:
                - id
                - products
              properties:
                id:
                  description: Уникальный идентификатор чека.
                  type: string
                  pattern: '^[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}$'
                # TODO: Не допускать пустые чеки
                products:
                  $ref: '#/definitions/ProductsList'
      responses:
        200:
          description: История сохранена.

parameters:
  ApiKey:
    name: api_key
    in: query
    description: Ключ API.
    required: true
    type: string
    pattern: '^[a-zA-Z0-9]{64}$'

definitions:
  Product:
    description: Уникальный идентификатор товара.
    type: string
    pattern: '^[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}$'
  ProductsList:
    type: array
    description: Список товаров.
    items:
      $ref: '#/definitions/Product'
